from ..._config import __use_jax__

if __use_jax__:
    try:
        import jax.numpy as jnp
        from jax.scipy import integrate

        jax_installed = True

    except ImportError:
        import numpy as jnp
        from scipy import integrate

        jax_installed = False
else:
    import numpy as jnp
    from scipy import integrate

    jax_installed = False


def get_coefficients(
    parameter_values_dict,
    model_kind,
    variant=None,
    covariance_prefactor_dict=None,
):
    fs8 = parameter_values_dict["fs8"]

    if model_kind in ["density", "full", "density_velocity"]:
        b1s8 = parameter_values_dict["b1s8"]
        b2s8 = parameter_values_dict["b2s8"]
        if variant in ["biaslink", "nosigmavv_biaslink"]:
            bss8 = -4 / 7 * (b1s8 - 1)
            b3nls8 = 32 / 315 * (b1s8 - 1)
        else:
            bss8 = parameter_values_dict["bss8"]
            b3nls8 = parameter_values_dict["b3nls8"]

        sigv1sq = parameter_values_dict["sigv1sq"]
        sigv2sq = parameter_values_dict["sigv2sq"]
        sigv3sq = parameter_values_dict["sigv3sq"]

    if model_kind in ["velocity", "full", "density_velocity"]:
        b1vs8 = parameter_values_dict["b1vs8"]
        b2vs8 = parameter_values_dict["b2vs8"]
        if variant in ["biaslink", "nosigmavv_biaslink"]:
            bsvs8 = -4 / 7 * (b1vs8 - 1)
            b3nlvs8 = 32 / 315 * (b1vs8 - 1)
        else:
            bsvs8 = parameter_values_dict["bsvs8"]
            b3nlvs8 = parameter_values_dict["b3nlvs8"]

        sigvv1sq = parameter_values_dict["sigvv1sq"]
        sigvv2sq = parameter_values_dict["sigvv2sq"]

    if "nosigmavv" in variant & model_kind == "velocity":
        raise ValueError(
            "The nosigmavv variant is not applicable for the velocity model."
        )

    if "nosigmavv" in variant:
        sigvv1sq = sigv1sq
        sigvv2sq = sigv2sq

    coefficients_dict = {}
    if model_kind in ["density", "full", "density_velocity"]:
        coefficients_dict["gg"] = [
            b1s8**2,
            b1s8 * b2s8,
            b1s8 * bss8,
            b1s8**2,
            b1s8**2,
            b2s8**2,
            bss8**2,
            b2s8 * bss8,
            b3nls8,
            fs8 * b1s8,
            fs8 * b1s8,
            fs8 * b1s8**2,
            fs8 * b1s8,
            fs8 * b1s8**2,
            fs8 * b2s8,
            fs8 * bss8,
            fs8 * b1s8 * b2s8,
            fs8 * b1s8 * bss8,
            fs8 * b3nls8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * b1s8**2 * sigv1sq,
            fs8**2 * b1s8 * b2s8 * sigv1sq,
            fs8**2 * b1s8 * bss8 * sigv1sq,
            fs8**2 * b1s8**2 * sigv1sq,
            fs8**2 * b1s8**2 * sigv1sq,
            fs8**2 * b2s8**2 * sigv1sq,
            fs8**2 * bss8**2 * sigv1sq,
            fs8**2 * b2s8 * bss8 * sigv1sq,
            fs8**2 * b3nls8 * sigv1sq,
            fs8**2 * b2s8,
            fs8**2 * bss8,
            fs8**2 * b2s8,
            fs8**2 * bss8,
            fs8**2,
            fs8**2,
            fs8**2 * b1s8,
            fs8**2 * b1s8**2,
            fs8**2 * b1s8**2,
            fs8**2 * b1s8,
            fs8**2,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1s8**2,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1s8**2,
            fs8**3 * sigv2sq * b2s8,
            fs8**3 * sigv2sq * bss8,
            fs8**3 * sigv2sq * b1s8 * b2s8,
            fs8**3 * sigv2sq * b1s8 * bss8,
            fs8**3 * sigv2sq * b3nls8,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8**4,
            fs8**4 * b1s8**3 * b2s8,
            fs8**4 * b1s8**3 * bss8,
            fs8**4 * b1s8**4,
            fs8**4 * b1s8**4,
            fs8**4 * b1s8**2 * b2s8**2,
            fs8**4 * b1s8**2 * bss8**2,
            fs8**4 * b1s8**2 * b2s8 * bss8,
            fs8**4 * b1s8**2 * b3nls8,
            fs8**4 * b1s8**4 * sigv3sq**2,
            fs8**4 * b1s8**3 * b2s8 * sigv3sq**2,
            fs8**4 * b1s8**3 * bss8 * sigv3sq**2,
            fs8**4 * b1s8**4 * sigv3sq**2,
            fs8**4 * b1s8**4 * sigv3sq**2,
            fs8**4 * b1s8**2 * b2s8**2 * sigv3sq**2,
            fs8**4 * b1s8**2 * bss8**2 * sigv3sq**2,
            fs8**4 * b1s8**2 * b2s8 * bss8 * sigv3sq**2,
            fs8**4 * b1s8**2 * b3nls8 * sigv3sq**2,
            fs8**3,
            fs8**3,
            fs8**3 * b1s8,
            fs8**3 * b1s8,
            fs8**3,
            fs8**3,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1s8**2 * sigv1sq,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1s8**2 * sigv1sq,
            fs8**3 * b2s8 * sigv1sq,
            fs8**3 * bss8 * sigv1sq,
            fs8**3 * b1s8 * b2s8 * sigv1sq,
            fs8**3 * b1s8 * bss8 * sigv1sq,
            fs8**3 * b3nls8 * sigv1sq,
            fs8**3 * sigv1sq,
            fs8**3 * sigv1sq,
            fs8**4 * sigv2sq,
            fs8**4 * sigv2sq,
            fs8**4 * b1s8 * sigv2sq,
            fs8**4 * sigv2sq,
            fs8**4 * b1s8 * sigv2sq,
            fs8**4 * sigv1sq * b1s8**2,
            fs8**4 * sigv1sq * b1s8**2,
            fs8**4,
            fs8**4,
            fs8**4,
            fs8**4 * b1s8**2 * sigv1sq**2,
            fs8**4 * b1s8 * b2s8 * sigv1sq**2,
            fs8**4 * b1s8 * bss8 * sigv1sq**2,
            fs8**4 * b1s8**2 * sigv1sq**2,
            fs8**4 * b1s8**2 * sigv1sq**2,
            fs8**4 * b2s8**2 * sigv1sq**2,
            fs8**4 * bss8**2 * sigv1sq**2,
            fs8**4 * b2s8 * bss8 * sigv1sq**2,
            fs8**4 * b3nls8 * sigv1sq**2,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
        ]

    if model_kind in ["full"]:
        coefficients_dict["gv"] = [
            fs8 * b1s8,
            fs8 * b1s8,
            fs8 * b1s8 * b1vs8,
            fs8 * b1s8,
            fs8 * b1vs8 * b1s8,
            fs8 * b2s8,
            fs8 * bss8,
            fs8 * b2s8 * b1vs8,
            fs8 * b1vs8 * bss8,
            fs8 * b3nlvs8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * b1s8,
            fs8**2 * sigv1sq * b1s8 * b1vs8,
            fs8**2 * sigv1sq * (b1s8 * b2vs8 + b1vs8 * b2s8),
            fs8**2 * sigv1sq * (b1s8 * bsvs8 + b1vs8 * bss8),
            fs8**2 * sigv1sq * b1s8 * b1vs8,
            fs8**2 * sigv1sq * b1s8 * b1vs8,
            fs8**2 * sigv1sq * b2s8 * b2vs8,
            fs8**2 * sigv1sq * bss8 * bsvs8,
            fs8**2 * sigv1sq * (b2vs8 * bss8 + b2s8 * bsvs8),
            fs8**2 * sigv1sq * b3nlvs8,
            fs8**2 * b2s8,
            fs8**2 * bss8,
            fs8**2 * b2s8,
            fs8**2 * bss8,
            fs8**2,
            fs8**2,
            fs8**2 * (b1s8 + b1vs8),
            fs8**2 * b1s8 * b1vs8,
            fs8**2 * b1s8 * b1vs8,
            fs8**2 * (b1s8 + b1vs8),
            fs8**2,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1s8 * b1vs8,
            fs8**3 * sigv2sq * b1s8,
            fs8**3 * sigv2sq * b1vs8 * b1s8,
            fs8**3 * sigv2sq * b2s8,
            fs8**3 * sigv2sq * bss8,
            fs8**3 * sigv2sq * b2s8 * b1vs8,
            fs8**3 * sigv2sq * b1vs8 * bss8,
            fs8**3 * sigv2sq * b3nlvs8,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8 * sigv3sq,
            fs8**4 * b1s8**2 * b1vs8**2,
            fs8**4 * b1s8 * b1vs8 * (b1s8 * b2vs8 + b1vs8 * b2s8),
            fs8**4 * b1s8 * b1vs8 * (b1s8 * bsvs8 + b1vs8 * bss8),
            fs8**4 * b1s8**2 * b1vs8**2,
            fs8**4 * b1s8**2 * b1vs8**2,
            fs8**4 * b1s8 * b1vs8 * b2s8 * b2vs8,
            fs8**4 * b1s8 * b1vs8 * bss8 * bsvs8,
            fs8**4 * b1s8 * b1vs8 * (b2vs8 * bss8 + b2s8 * bsvs8),
            fs8**4 * b1s8 * b1vs8 * b3nlvs8,
            fs8**4 * b1s8**2 * b1vs8**2 * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * (b1s8 * b2vs8 + b1vs8 * b2s8) * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * (b1s8 * bsvs8 + b1vs8 * bss8) * sigv3sq**2,
            fs8**4 * b1s8**2 * b1vs8**2 * sigv3sq**2,
            fs8**4 * b1s8**2 * b1vs8**2 * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * b2s8 * b2vs8 * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * bss8 * bsvs8 * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * (b2vs8 * bss8 + b2s8 * bsvs8) * sigv3sq**2,
            fs8**4 * b1s8 * b1vs8 * b3nlvs8 * sigv3sq**2,
            fs8**3,
            fs8**3,
            fs8**3 * b1s8,
            fs8**3 * b1s8,
            fs8**3,
            fs8**3,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1s8 * b1vs8 * sigv1sq,
            fs8**3 * b1s8 * sigv1sq,
            fs8**3 * b1vs8 * b1s8 * sigv1sq,
            fs8**3 * b2s8 * sigv1sq,
            fs8**3 * bss8 * sigv1sq,
            fs8**3 * b2s8 * b1vs8 * sigv1sq,
            fs8**3 * b1vs8 * bss8 * sigv1sq,
            fs8**3 * b3nlvs8 * sigv1sq,
            fs8**3 * sigv1sq,
            fs8**3 * sigv1sq,
            fs8**4 * sigv2sq,
            fs8**4 * sigv2sq,
            fs8**4 * (b1s8 + b1vs8) * sigv2sq,
            fs8**4 * sigv2sq,
            fs8**4 * (b1s8 + b1vs8) * sigv2sq,
            fs8**4 * sigv1sq * b1s8 * b1vs8,
            fs8**4 * sigv1sq * b1s8 * b1vs8,
            fs8**4,
            fs8**4,
            fs8**4,
            fs8**4 * b1s8 * b1vs8 * sigv1sq**2,
            fs8**4 * (b1s8 * b2vs8 + b1vs8 * b2s8) * sigv1sq**2,
            fs8**4 * (b1s8 * bsvs8 + b1vs8 * bss8) * sigv1sq**2,
            fs8**4 * b1s8 * b1vs8 * sigv1sq**2,
            fs8**4 * b1s8 * b1vs8 * sigv1sq**2,
            fs8**4 * b2s8 * b2vs8 * sigv1sq**2,
            fs8**4 * bss8 * bsvs8 * sigv1sq**2,
            fs8**4 * (b2vs8 * bss8 + b2s8 * bsvs8) * sigv1sq**2,
            fs8**4 * b3nlvs8 * sigv1sq**2,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b1s8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
            fs8**4 * b2s8 * sigv1sq,
            fs8**4 * bss8 * sigv1sq,
        ]

    if model_kind in ["velocity", "full", "density_velocity"]:
        coefficients_dict["vv"] = [
            fs8**2,
            fs8**2,
            fs8**2 * b1vs8,
            fs8**2 * b1vs8**2,
            fs8**2 * b1vs8**2,
            fs8**2 * b1vs8,
            fs8**2,
            fs8**3,
            fs8**3,
            fs8**3 * b1vs8,
            fs8**3 * b1vs8,
            fs8**3,
            fs8**3,
            fs8**3 * b1vs8 * sigvv1sq,
            fs8**3 * b1vs8 * sigvv1sq,
            fs8**3 * b1vs8**2 * sigvv1sq,
            fs8**3 * b1vs8 * sigvv1sq,
            fs8**3 * b1vs8**2 * sigvv1sq,
            fs8**3 * b2vs8 * sigvv1sq,
            fs8**3 * bsvs8 * sigvv1sq,
            fs8**3 * b1vs8 * b2vs8 * sigvv1sq,
            fs8**3 * b1vs8 * bsvs8 * sigvv1sq,
            fs8**3 * b3nlvs8 * sigvv1sq,
            fs8**3 * sigvv1sq,
            fs8**3 * sigvv1sq,
            fs8**4 * sigvv2sq,
            fs8**4 * sigvv2sq,
            fs8**4 * b1vs8 * sigvv2sq,
            fs8**4 * sigvv2sq,
            fs8**4 * b1vs8 * sigvv2sq,
            fs8**4 * sigvv1sq * b1vs8**2,
            fs8**4 * sigvv1sq * b1vs8**2,
            fs8**4,
            fs8**4,
            fs8**4,
            fs8**4 * b1vs8**2 * sigvv1sq**2,
            fs8**4 * b1vs8 * b2vs8 * sigvv1sq**2,
            fs8**4 * b1vs8 * bsvs8 * sigvv1sq**2,
            fs8**4 * b1vs8**2 * sigvv1sq**2,
            fs8**4 * b1vs8**2 * sigvv1sq**2,
            fs8**4 * b2vs8**2 * sigvv1sq**2,
            fs8**4 * bsvs8**2 * sigvv1sq**2,
            fs8**4 * b2vs8 * bsvs8 * sigvv1sq**2,
            fs8**4 * b3nlvs8 * sigvv1sq**2,
            fs8**4 * b1vs8 * sigvv1sq,
            fs8**4 * b1vs8 * sigvv1sq,
            fs8**4 * b1vs8 * sigvv1sq,
            fs8**4 * b1vs8 * sigvv1sq,
            fs8**4 * b2vs8 * sigvv1sq,
            fs8**4 * bsvs8 * sigvv1sq,
            fs8**4 * b2vs8 * sigvv1sq,
            fs8**4 * bsvs8 * sigvv1sq,
            fs8**4 * b2vs8 * sigvv1sq,
            fs8**4 * bsvs8 * sigvv1sq,
            fs8**4 * b2vs8 * sigvv1sq,
            fs8**4 * bsvs8 * sigvv1sq,
        ]

    prefactor_dict = get_cov_matrix_prefactor(
        model_kind,
        covariance_prefactor_dict,
    )

    for key in coefficients_dict.keys():
        coefficients_dict[key] = [
            coefficients_dict[key][i] * prefactor_dict[key][i]
            for i in range(len(coefficients_dict[key]))
        ]

    return coefficients_dict


def get_diagonal_coefficients(parameter_values_dict, model_kind):
    coefficients_dict = {}
    if model_kind in ["density", "full", "density_velocity"]:
        coefficients_dict["gg"] = 0.0
    if model_kind in ["velocity", "full", "density_velocity"]:
        coefficients_dict["vv"] = parameter_values_dict["sigv"] ** 2
    return coefficients_dict


def get_cov_matrix_prefactor(
    model_kind,
    covariance_prefactor_dict,
):
    prefactor_dict = {}

    if model_kind in ["density", "full", "density_velocity"]:

        D_growth_z_density = covariance_prefactor_dict["D_growth_z_density"]

        field_terms_density = [
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**3,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
        ]

        if isinstance(D_growth_z_density, float):
            prefactor_density = [
                field_terms_density[i] ** 2 for i in range(len(field_terms_density))
            ]
        else:
            prefactor_density = [
                jnp.outer(field_terms_density[i], field_terms_density[i])
                for i in range(len(field_terms_density))
            ]
        prefactor_dict["gg"] = prefactor_density

    if model_kind in ["velocity", "full", "density_velocity"]:

        a_z_velocity = covariance_prefactor_dict["a_z_velocity"]
        H_z_velocity = covariance_prefactor_dict["H_z_velocity"]
        D_growth_z_velocity = covariance_prefactor_dict["D_growth_z_velocity"]

        field_terms_velocity = [
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
        ]

        if isinstance(a_z_velocity, float):
            prefactor_velocity = [
                field_terms_velocity[i] ** 2 for i in range(len(field_terms_velocity))
            ]
        else:
            prefactor_velocity = [
                jnp.outer(field_terms_velocity[i], field_terms_velocity[i])
                for i in range(len(field_terms_velocity))
            ]

        prefactor_dict["vv"] = prefactor_velocity

    if model_kind in ["full"]:

        field_terms_density_cross = [
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**3,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density**4,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
            D_growth_z_density**2,
        ]
        field_terms_velocity_cross = [
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**3 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**4 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
            D_growth_z_velocity**2 * a_z_velocity * H_z_velocity,
        ]

        if isinstance(D_growth_z_velocity, float):
            prefactor_cross = [
                field_terms_density_cross[i] * field_terms_velocity_cross[i]
                for i in range(len(field_terms_density_cross))
            ]
        else:
            prefactor_cross = [
                jnp.outer(field_terms_density_cross[i], field_terms_velocity_cross[i])
                for i in range(len(field_terms_density_cross))
            ]
        prefactor_dict["gv"] = prefactor_cross

    return prefactor_dict


# CR - grids terms to verify, also linked to mu1, mu2 decomposition to account for wide-angle effects


def get_power_spectrum_dictionary(
    power_spectrum_array,
    grid_window_density=1.0,
    grid_window_velocity=1.0,
):

    k = power_spectrum_array[0, 0:]
    Pl = power_spectrum_array[1, 0:]
    I00 = power_spectrum_array[2, 0:]
    I01 = power_spectrum_array[3, 0:]
    I02 = power_spectrum_array[4, 0:]
    I03 = power_spectrum_array[5, 0:]
    I10 = power_spectrum_array[6, 0:]
    I11 = power_spectrum_array[7, 0:]
    I12 = power_spectrum_array[8, 0:]
    I13 = power_spectrum_array[9, 0:]
    I20 = power_spectrum_array[10, 0:]
    I21 = power_spectrum_array[11, 0:]
    I22 = power_spectrum_array[12, 0:]
    I23 = power_spectrum_array[13, 0:]
    I30 = power_spectrum_array[14, 0:]
    I31 = power_spectrum_array[15, 0:]
    I32 = power_spectrum_array[16, 0:]
    I33 = power_spectrum_array[17, 0:]
    J00 = power_spectrum_array[18, 0:]
    J01 = power_spectrum_array[19, 0:]
    J02 = power_spectrum_array[20, 0:]
    J10 = power_spectrum_array[21, 0:]
    J11 = power_spectrum_array[22, 0:]
    J20 = power_spectrum_array[23, 0:]
    K00 = power_spectrum_array[24, 0:]
    Ks00 = power_spectrum_array[25, 0:]
    K01 = power_spectrum_array[26, 0:]
    Ks01 = power_spectrum_array[27, 0:]
    Ks02 = power_spectrum_array[28, 0:]
    K10 = power_spectrum_array[29, 0:]
    Ks10 = power_spectrum_array[30, 0:]
    K11 = power_spectrum_array[31, 0:]
    Ks11 = power_spectrum_array[32, 0:]
    K20 = power_spectrum_array[33, 0:]
    Ks20 = power_spectrum_array[34, 0:]
    K30 = power_spectrum_array[35, 0:]
    Ks30 = power_spectrum_array[36, 0:]
    sig3_squre = power_spectrum_array[37, 0:]
    sig4_squre = (
        1.0
        / (24.0 * jnp.pi * jnp.pi)
        * (integrate.simpson((I23 + 2.0 / 3.0 * I32 + I33 / 5.0) / k**2, k))
    )

    power_spectrum_dict = {
        "gg": [
            [k, Pl * grid_window_density**2],
            [k, K00 * grid_window_density**2],
            [k, Ks00 * grid_window_density**2],
            [k, I00 * grid_window_density**2],
            [k, J00 * Pl * grid_window_density**2],
            [k, K01 * grid_window_density**2],
            [k, Ks01 * grid_window_density**2],
            [k, Ks02 * grid_window_density**2],
            [k, sig3_squre * Pl * grid_window_density**2],
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, I01 * grid_window_density * grid_window_velocity],
            [k, I10 * grid_window_density * grid_window_velocity],
            [k, J01 * Pl * grid_window_density * grid_window_velocity],
            [k, J10 * Pl * grid_window_density * grid_window_velocity],
            [k, K10 * grid_window_density * grid_window_velocity],
            [k, Ks10 * grid_window_density * grid_window_velocity],
            [k, K11 * grid_window_density * grid_window_velocity],
            [k, Ks11 * grid_window_density * grid_window_velocity],
            [k, sig3_squre * Pl * grid_window_density * grid_window_velocity],
            [k, I02 * grid_window_density * grid_window_velocity],
            [k, I20 * grid_window_density * grid_window_velocity],
            [k, J02 * Pl * grid_window_density * grid_window_velocity],
            [k, J20 * Pl * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, K00 * grid_window_density * grid_window_velocity],
            [k, Ks00 * grid_window_density * grid_window_velocity],
            [k, I00 * grid_window_density * grid_window_velocity],
            [k, J00 * Pl * grid_window_density * grid_window_velocity],
            [k, K01 * grid_window_density * grid_window_velocity],
            [k, Ks01 * grid_window_density * grid_window_velocity],
            [k, Ks02 * grid_window_density * grid_window_velocity],
            [k, sig3_squre * Pl * grid_window_density * grid_window_velocity],
            [k, K20 * grid_window_density * grid_window_velocity],
            [k, Ks20 * grid_window_density * grid_window_velocity],
            [k, K30 * grid_window_density * grid_window_velocity],
            [k, Ks30 * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, I11 * grid_window_density * grid_window_velocity],
            [k, I22 * grid_window_density * grid_window_velocity],
            [k, I31 * grid_window_density * grid_window_velocity],
            [k, I13 * grid_window_density * grid_window_velocity],
            [k, J10 * Pl * grid_window_density * grid_window_velocity],
            [k, J11 * Pl * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_velocity**2],
            [k, I01 * grid_window_velocity**2],
            [k, I10 * grid_window_velocity**2],
            [k, J01 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, K10 * grid_window_velocity**2],
            [k, Ks10 * grid_window_velocity**2],
            [k, K11 * grid_window_velocity**2],
            [k, Ks11 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I02 * grid_window_velocity**2],
            [k, I20 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, sig4_squre * Pl * grid_window_velocity**2],
            [k, K00 * sig4_squre * grid_window_velocity**2],
            [k, Ks00 * sig4_squre * grid_window_velocity**2],
            [k, I00 * sig4_squre * grid_window_velocity**2],
            [k, J00 * sig4_squre * Pl * grid_window_velocity**2],
            [k, K01 * sig4_squre * grid_window_velocity**2],
            [k, Ks01 * sig4_squre * grid_window_velocity**2],
            [k, Ks02 * sig4_squre * grid_window_velocity**2],
            [k, sig3_squre * sig4_squre * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, K00 * grid_window_velocity**2],
            [k, Ks00 * grid_window_velocity**2],
            [k, I00 * grid_window_velocity**2],
            [k, J00 * Pl * grid_window_velocity**2],
            [k, K01 * grid_window_velocity**2],
            [k, Ks01 * grid_window_velocity**2],
            [k, Ks02 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I12 * grid_window_velocity**2],
            [k, I21 * grid_window_velocity**2],
            [k, I03 * grid_window_velocity**2],
            [k, I30 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I01 * grid_window_velocity**2],
            [k, I10 * grid_window_velocity**2],
            [k, J01 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, K10 * grid_window_velocity**2],
            [k, Ks10 * grid_window_velocity**2],
            [k, K11 * grid_window_velocity**2],
            [k, Ks11 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, (I01 + I10) * grid_window_velocity**2],
            [k, (J01 + J10) * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I11 * grid_window_velocity**2],
            [k, I22 * grid_window_velocity**2],
            [k, J11 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, I13 * grid_window_velocity**2],
            [k, I31 * grid_window_velocity**2],
            [k, I23 * grid_window_velocity**2],
            [k, I32 * grid_window_velocity**2],
            [k, I33 * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, K00 * grid_window_velocity**2],
            [k, Ks00 * grid_window_velocity**2],
            [k, I00 * grid_window_velocity**2],
            [k, J00 * Pl * grid_window_velocity**2],
            [k, K01 * grid_window_velocity**2],
            [k, Ks01 * grid_window_velocity**2],
            [k, Ks02 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I02 * grid_window_velocity**2],
            [k, I20 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
        ],
        "gv": [
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, I01 * grid_window_density * grid_window_velocity],
            [k, I10 * grid_window_density * grid_window_velocity],
            [k, J01 * Pl * grid_window_density * grid_window_velocity],
            [k, J10 * Pl * grid_window_density * grid_window_velocity],
            [k, K10 * grid_window_density * grid_window_velocity],
            [k, Ks10 * grid_window_density * grid_window_velocity],
            [k, K11 * grid_window_density * grid_window_velocity],
            [k, Ks11 * grid_window_density * grid_window_velocity],
            [k, sig3_squre * Pl * grid_window_density * grid_window_velocity],
            [k, I02 * grid_window_density * grid_window_velocity],
            [k, I20 * grid_window_density * grid_window_velocity],
            [k, J02 * Pl * grid_window_density * grid_window_velocity],
            [k, J20 * Pl * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, K00 * grid_window_density * grid_window_velocity],
            [k, Ks00 * grid_window_density * grid_window_velocity],
            [k, I00 * grid_window_density * grid_window_velocity],
            [k, J00 * Pl * grid_window_density * grid_window_velocity],
            [k, K01 * grid_window_density * grid_window_velocity],
            [k, Ks01 * grid_window_density * grid_window_velocity],
            [k, Ks02 * grid_window_density * grid_window_velocity],
            [k, sig3_squre * Pl * grid_window_density * grid_window_velocity],
            [k, K20 * grid_window_density * grid_window_velocity],
            [k, Ks20 * grid_window_density * grid_window_velocity],
            [k, K30 * grid_window_density * grid_window_velocity],
            [k, Ks30 * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_density * grid_window_velocity],
            [k, I11 * grid_window_density * grid_window_velocity],
            [k, I22 * grid_window_density * grid_window_velocity],
            [k, I31 * grid_window_density * grid_window_velocity],
            [k, I13 * grid_window_density * grid_window_velocity],
            [k, J10 * Pl * grid_window_density * grid_window_velocity],
            [k, J11 * Pl * grid_window_density * grid_window_velocity],
            [k, Pl * grid_window_velocity**2],
            [k, I01 * grid_window_velocity**2],
            [k, I10 * grid_window_velocity**2],
            [k, J01 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, K10 * grid_window_velocity**2],
            [k, Ks10 * grid_window_velocity**2],
            [k, K11 * grid_window_velocity**2],
            [k, Ks11 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I02 * grid_window_velocity**2],
            [k, I20 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, sig4_squre * Pl * grid_window_velocity**2],
            [k, K00 * sig4_squre * grid_window_velocity**2],
            [k, Ks00 * sig4_squre * grid_window_velocity**2],
            [k, I00 * sig4_squre * grid_window_velocity**2],
            [k, J00 * sig4_squre * Pl * grid_window_velocity**2],
            [k, K01 * sig4_squre * grid_window_velocity**2],
            [k, Ks01 * sig4_squre * grid_window_velocity**2],
            [k, Ks02 * sig4_squre * grid_window_velocity**2],
            [k, sig3_squre * sig4_squre * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, K00 * grid_window_velocity**2],
            [k, Ks00 * grid_window_velocity**2],
            [k, I00 * grid_window_velocity**2],
            [k, J00 * Pl * grid_window_velocity**2],
            [k, K01 * grid_window_velocity**2],
            [k, Ks01 * grid_window_velocity**2],
            [k, Ks02 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I12 * grid_window_velocity**2],
            [k, I21 * grid_window_velocity**2],
            [k, I03 * grid_window_velocity**2],
            [k, I30 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I01 * grid_window_velocity**2],
            [k, I10 * grid_window_velocity**2],
            [k, J01 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, K10 * grid_window_velocity**2],
            [k, Ks10 * grid_window_velocity**2],
            [k, K11 * grid_window_velocity**2],
            [k, Ks11 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, (I01 + I10) * grid_window_velocity**2],
            [k, (J01 + J10) * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I11 * grid_window_velocity**2],
            [k, I22 * grid_window_velocity**2],
            [k, J11 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, I13 * grid_window_velocity**2],
            [k, I31 * grid_window_velocity**2],
            [k, I23 * grid_window_velocity**2],
            [k, I32 * grid_window_velocity**2],
            [k, I33 * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, K00 * grid_window_velocity**2],
            [k, Ks00 * grid_window_velocity**2],
            [k, I00 * grid_window_velocity**2],
            [k, J00 * Pl * grid_window_velocity**2],
            [k, K01 * grid_window_velocity**2],
            [k, Ks01 * grid_window_velocity**2],
            [k, Ks02 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I02 * grid_window_velocity**2],
            [k, I20 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
        ],
        "vv": [
            [k, Pl * grid_window_velocity**2],
            [k, I11 * grid_window_velocity**2],
            [k, I22 * grid_window_velocity**2],
            [k, I31 * grid_window_velocity**2],
            [k, I13 * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, J11 * Pl * grid_window_velocity**2],
            [k, I12 * grid_window_velocity**2],
            [k, I21 * grid_window_velocity**2],
            [k, I03 * grid_window_velocity**2],
            [k, I30 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I01 * grid_window_velocity**2],
            [k, I10 * grid_window_velocity**2],
            [k, J01 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, K10 * grid_window_velocity**2],
            [k, Ks10 * grid_window_velocity**2],
            [k, K11 * grid_window_velocity**2],
            [k, Ks11 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, (I01 + I10) * grid_window_velocity**2],
            [k, (J01 + J10) * Pl * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, I11 * grid_window_velocity**2],
            [k, I22 * grid_window_velocity**2],
            [k, J11 * Pl * grid_window_velocity**2],
            [k, J10 * Pl * grid_window_velocity**2],
            [k, I13 * grid_window_velocity**2],
            [k, I31 * grid_window_velocity**2],
            [k, I23 * grid_window_velocity**2],
            [k, I32 * grid_window_velocity**2],
            [k, I33 * grid_window_velocity**2],
            [k, Pl * grid_window_velocity**2],
            [k, K00 * grid_window_velocity**2],
            [k, Ks00 * grid_window_velocity**2],
            [k, I00 * grid_window_velocity**2],
            [k, J00 * Pl * grid_window_velocity**2],
            [k, K01 * grid_window_velocity**2],
            [k, Ks01 * grid_window_velocity**2],
            [k, Ks02 * grid_window_velocity**2],
            [k, sig3_squre * Pl * grid_window_velocity**2],
            [k, I02 * grid_window_velocity**2],
            [k, I20 * grid_window_velocity**2],
            [k, J02 * Pl * grid_window_velocity**2],
            [k, J20 * Pl * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
            [k, K20 * grid_window_velocity**2],
            [k, Ks20 * grid_window_velocity**2],
            [k, K30 * grid_window_velocity**2],
            [k, Ks30 * grid_window_velocity**2],
        ],
    }

    return power_spectrum_dict
